### ISSUE TITLE
Application may forget previous oAuth requests

### ISSUE THREAD

**Issue by jgpacker** [Zverik/Level0#19]
Recently, for some reason the Level0 website is asking me to log in everyday if I want to use it.

I went to my OSM account to look at something and discovered that Level0 had around 10 active OAuth requests (see https://www.openstreetmap.org/user/u/oauth_clients).

My knowledge of OAuth is very superficial, so I have no idea what the problem may be.

**Comment by Zverik** [comment]
This is probably fixed, since I have been staying logged in for almost a month. Seems that all I had to do is to specify a dedicated directory on the server to store session info.
