### ISSUE TITLE
Loading from Overpass API problem

### ISSUE THREAD

**Issue by tilmanb** [Zverik/Level0#21]
When trying to load data from Overpass API level0 does not read data.

Level0 locale is german.

1. Open level0
2. paste `http://overpass-api.de/api/interpreter?data=[out%3Axml][timeout%3A25]%3B%28way%2823159132%29%29%3Bout%20body%3B%3E%3Bout%20skel%20qt%3B ` as URL
3. click "replace in editor"

level0 displays lots of "no version for object ..." errors.

This(?) also has broken the level0 links coming from taginfo, e.g. from here: http://taginfo.openstreetmap.org/keys/?key=maxspeed%3D30#overview

**Comment by Zverik** [comment]
Yes, Level0 expects versions for objects. Please use `meta` for `out` instead of `body` and `skel`:
```
http://overpass-api.de/api/interpreter?data=[out%3Axml][timeout%3A25]%3B%28way%2823159132%29%29%3Bout%20meta%3B%3E%3Bout%20meta%20qt%3B
```
As for broken level0 links, these are not broken, but the overpass api returns empty data.
