### ISSUE TITLE
Login returns http 500

### ISSUE THREAD

**Issue by cascafico** [Zverik/Level0#23]
I followed all wiki steps, but still logging-in returns an error http 500. Here's oauth client settings:

Nome (Richiesto): LamponeLevel0
URL applicazione principale (Richiesto): http://lampone.zapto.org/Level0/www/index.php

Requested authorizations:
- leggi le sue preferenze utente (read user preferences)
- modifica la mappa (modify map)

in config.php I inserted only 
- Chiave del consumatore (user key) 
- Codice segreto dell'utilizzatore (user secret code)

deploy_locale ran smoothly

Is there anything I miss?

**Comment by Zverik** [comment]
Is there anything related in the apache error log?
Does the error happen when you press "login", or after you return from osm.org?

**Comment by cascafico** [comment]
You are right! 

Here's nginx error:

2015/11/27 18:10:21 [error] 2600#0: *40465 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class 'OAuth' not found in /var/www/Level0/www/osmapi.php on line 6" while reading response header from upstream, client: x..x.x.x, server: localhost, request: "POST /Level0/www/index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "lampone.zapto.org", referrer: "http://lampone.zapto.org/Level0/www/?url=node/429973805"

It happens when I press Login, so I cannot login at all.

**Comment by Zverik** [comment]
Right, you need to [install OAuth PECL package](http://php.net/manual/en/oauth.installation.php).

**Comment by cascafico** [comment]
Thanks! It was a lilltle hard building the extension for my basic Debian Raspberry but in worked, eventually.

**Comment by Zverik** [comment]
Great :)
