### ISSUE TITLE
Redirecting to index.html

### ISSUE THREAD

**Issue by cascafico** [Zverik/Level0#24]
Sorry for bothering once again.

http://lampone.zapto.org/Level0/www

Eventually I can login into osm account, but after been authorized, there is no redirection; osm page generates link to application as expected; if I follow the link I'm back again in the initial non-logged Level0 page.

I read in nginx error.log:
rewrite or internal redirection cycle while internally redirecting to "/index.html"

As far as you know, should inspect nginx conf or could be caused by Level0 files stored in subfolder (not document root)?

Openstreetmap oauth page (I left last 3 unchanged):

Chiave del consumatore: xxxx
Codice segreto dell'utilizzatore: yyyy
URL del token di richiesta: https://www.openstreetmap.org/oauth/request_token
URL del token di accesso: https://www.openstreetmap.org/oauth/access_token
Autorizza URL: https://www.openstreetmap.org/oauth/authorize

**Comment by Zverik** [comment]
I have this URL in "Callback URL" field: `http://level0.osmz.ru/index.php?action=callback`

**Comment by cascafico** [comment]
It worked. One again, thanks.

**Comment by martinum4** [comment]
I had the same issue, maybe add this to the readme?
