### ISSUE TITLE
delete ways before nodes?

### ISSUE THREAD

**Issue by polarbearing** [Zverik/Level0#27]
Trying to delete a few simple ways today by setting minus signs in front of the 'way' and 'node' statements, the upload failed with error 412 (Precondition Failed), complaining that a node was still used by a way, which I however tried to delete in the same changeset. In L0 statement, each way deletion appeared before its nodes.

Looking at the OsmChange contents I found all nodes being sorted numerically, followed by the numerically sorted ways. Maybe the ways should be listed first?

(I worked around for that edit by removing only the ways in the first changeset, then loading only the nodes via the temporary OsmChange file, and deleting them afterwords.)

**Comment by Zverik** [comment]
Thanks for reminding about this, I've encountered the issue, but forgot to add it here.
I'll fix this a bit later.

**Comment by polarbearing** [comment]
Tnx. For some reason, the error-412-attempts do not show up in my changeset history. Isn't there a CS opened before the upload attempt? Or do the erratic CSs just not show up? (probably the latter, because my edit count went up a bit more than the 2 successful CSs)

**Comment by Zverik** [comment]
Fixed.
