### ISSUE TITLE
cannot open data with '"' from overpass

### ISSUE THREAD

**Issue by malenki** [Zverik/Level0#29]
When trying to open Level0 with some data from overpass API which contains '"' like [this call](http://level0.osmz.ru/?url=http%3A%2F%2Foverpass-api.de%2Fapi%2Finterpreter%3Fdata%3D%255Bout%253Axml%255D%253B%28node%255B%2522opening_hours%2522%253D%2522%255C%2522by%2520appointment%2520only%2522%2522%255D%253Bway%255B%2522opening_hours%2522%253D%2522%255C%2522by%2520appointment%2520only%2522%2522%255D%253B%253E%253Brel%255B%2522opening_hours%2522%253D%2522%255C%2522by%2520appointment%2520only%2522%2522%255D%253B%29%253Bout%2520meta%253B) the editor complains:
`Failed to open XML stream`
and doesn't show any data loaded.
I discovered this issue while looking at "opening hours" in taginfo; e.g.: 
http://taginfo.osm.org/tags/opening_hours=%22by%20appointment%20only%22#

**Comment by Zverik** [comment]
You've actually found a bug in the taginfo, fixing it in https://github.com/joto/taginfo/pull/174

**Comment by malenki** [comment]
Jochen pointed me to Level0 since it was the editors fault. :)  
Anyway, thank you for the fix.
