### ISSUE TITLE
source=* tag for changeset

### ISSUE THREAD

**Issue by polarbearing** [Zverik/Level0#36]
It would be helpful to have, beside the field for the changeset comment,  a form field for the changeset ```source=*``` tag. 

There was a fix provided for #7 and #12, but I cannot see where a source tag is added in the code?

**Comment by Zverik** [comment]
Write at the top of text area:
```
changeset
source=whatever
```

And it will set the changeset tag `source` to `whatever`.

**Comment by polarbearing** [comment]
Understood. I propose to document this feature, [please review](https://wiki.openstreetmap.org/wiki/Level0#Changeset_tags).

**Comment by Zverik** [comment]
Looks good, thank you!
