### ISSUE TITLE
Accept URLs that will take you directly to editing an object

### ISSUE THREAD

**Issue by b-jazz** [Zverik/Level0#41]
I want to auto-generate URLs like https://level0.osmz.ru/way/123456 that will, when clicked/visited, load that particular object in the editor and save me the effort of having to copy/paste a URL into the text field and click Add to editor.

**Comment by Zverik** [comment]
Do you have control over URL generator? If yes, you can use `http://level0.osmz.ru/?url=w423` or `http://level0.osmz.ru/?url=w423!` (with `!`) to get member objects.

**Comment by b-jazz** [comment]
Oh, fantastic. I was trying to find documentation showing how to do that. Either I missed it or it doesn't exist. If it doesn't exist, maybe it could be added.

**Comment by b-jazz** [comment]
Just found it:
> To open the editor with a preloaded object or map region, use "url" query parameter: e.g. http://level0.osmz.ru/?url=node/240095754

Thanks! Love the editor! It really fills out my toolbox of editors and there are several uses for it the other more full-featured editors just don't handle well.
