### ISSUE TITLE
Login fails

### ISSUE THREAD

**Issue by matkoniecz** [Zverik/Level0#48]
I get "Error! There is no OAuth secret!" on login attempt.

Firefox 85.0.1

**Comment by mueschel** [comment]
That looks like a storage issue. Even if you are still logged in, editing doesn't work because there is no data about the objects stored ("no base data" or similar, I don't know the precise English error message)

**Comment by Zverik** [comment]
Thanks @mueschel, it really was. Try again Mateusz, please.

**Comment by mueschel** [comment]
For me both logging in and editing works again. Thanks!

**Comment by matkoniecz** [comment]
Thanks, now it works!

**Comment by bugdebugger** [comment]
@Zverik
Seems the issue is back.
First I got `No base data for ...` while still logged in.
After logging out I can't log in anymore because of `Error! There is no OAuth secret!`

**Comment by matkoniecz** [comment]
I can confirm that the same symptoms are back.

**Comment by bugdebugger** [comment]
Could relogin in the meantime.

Maybe a transient storage issue? If the `.base` files fill up the available space faster then some cron job cleans them out

**Comment by mueschel** [comment]
> Maybe a transient storage issue?

Same problem is back again.

**Comment by mueschel** [comment]
Same problem is back again.

**Comment by Zverik** [comment]
Again the free disk space issue — fixed it for good, hopefully. Thanks for the notice!

**Comment by mueschel** [comment]
Same problem is back again.

**Comment by Zverik** [comment]
Fixed. Sorry :)
