### ISSUE TITLE
SSL certificate error

### ISSUE THREAD

**Issue by mueschel** [Zverik/Level0#56]
Hi,
your server has an issue accepting the SSL certificate of osm.org

`OAuth error -1: making the request failed (Peer certificate cannot be authenticated with given CA certificates)`

That's likely related to the change of Root certificate by Let's Encrypt.

**Comment by Zverik** [comment]
Yeah, I use an outdated OS that didn't have the new root certificate. Added it manually, now the authorization works again. Thanks for the tip!
