### ISSUE TITLE
Undelete a node using Level0 editor seems to not be working

### ISSUE THREAD

**Issue by fititnt** [Zverik/Level0#80]
Related question/issue: https://help.openstreetmap.org/questions/81087/how-to-undelete-a-node-using-level0-editor

---

Is the functionality of https://wiki.openstreetmap.org/wiki/Level0#Undelete_a_node (undeleting a node) still working?

I attempted undelete a node like the documentation and do other edit, however it does not undeleted the deleted node. Yes, I do know exist other tools, however was a simple change.

More context:
- "Download .osm" displayed all data, as in the editor
- "Show osmChange" displayed other changes, but not the undelete (so

**Comment by maro-21** [comment]
If there have been no recent changes to the code, it should work. I do this from time to time and it works for me. Write what steps you took to undelete the node and what message you saw.

**Comment by fititnt** [comment]
Yes, I noticed it had no recent code changes.

Not today, but seems reasonable I provide step by step, so I will do it with dummy data later

**Comment by fititnt** [comment]
I will use node/9560774926 (created as test node by someone else as example. Will add screenshots on the relevant steps.

Following the current version of documentation on https://wiki.openstreetmap.org/wiki/Level0

Undelete a node
> 1. Open the node's page on osm.org: e.g. https://www.openstreetmap.org/node/345345

Ok, would be this https://www.openstreetmap.org/node/9560774926


> 2. Check that it is deleted and find its version.


by https://www.openstreetmap.org/node/9560774926, this case, would be n9560774926 version 1. The version 2 was the deleted one.

> 3. Enter n345345.W into Level0 editor's URL field, where 345345 is the node's identifier, and W is its version minus one (e.g. 2 if the version was 3).

Ok, on this case would be n9560774926.1

![Screenshot from 2024-07-17 19-51-26](https://github.com/user-attachments/assets/746a2b31-987b-4452-932e-893ee18530e2)


4. Check that coordinates are there, then add the deletion version to the node's identifier after a dot, like that: "node 345345.3: <lat>, <lon>.

Ok, with coordinates, the browser shows this

```
node 9560774926: -30.0318242, -51.2221417
```

![Screenshot from 2024-07-17 19-55-59](https://github.com/user-attachments/assets/2e51cbde-4a96-42ea-846e-87fd133af913)


> 5. Upload changes (see steps 6-7 of editing a POI).
> (from https://wiki.openstreetmap.org/wiki/Level0#Edit_a_POI_tags)
> > 6. Press Log in button and the press Accept (or whatever osm.org site asks).
> > 7. Type a changeset comment (e.g. updated opening hours) and press Upload to OSM.

Used the upload comment "undelete test. See https://github.com/Zverik/Level0/issues/80"

![Screenshot from 2024-07-17 19-56-09](https://github.com/user-attachments/assets/b202718e-298f-47d4-b76c-af25a6d9b3be)

One error message "Nothing to upload." appears

(Note: one difference betwen the documentation and my test is at step 6, the account already is logged in. Unsure if this is the problem, because it would works for other edits)

**Comment by maro-21** [comment]
You didn't complete step four:

> 4\. then add the deletion version to the node's identifier after a dot, like that: "node 345345.3: , .

It this case it would be `node 9560774926.2: -30.0318242, -51.2221417`

**Comment by fititnt** [comment]
Oh, that explains. Thank you. I will post the screenshots here (in case anyone needs to know in the future), and then will close this issue.

For the object `https://www.openstreetmap.org/node/9560774926/history` version 2, the code used would need to be

```
node 9560774926.2: -30.0318242, -51.2221417
```

---
![Screenshot from 2024-07-19 00-29-57](https://github.com/user-attachments/assets/da12e5d6-06ed-4468-82c4-1a3eb47738db)

---
Then this time instead of "Nothing to upload" will appear the link for the changeset (this one) https://www.openstreetmap.org/changeset/154124990

![Screenshot from 2024-07-19 00-30-07](https://github.com/user-attachments/assets/52c60ba0-8ebd-44f3-934e-4e7a18e530c9)

---

Thank you @maro-21  !
